### اختبار رفع وتحليل ملف
POST http://localhost:5000/api/cv/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="userId"

1
------WebKitFormBoundary
Content-Disposition: form-data; name="cvFile"; filename="HCI_Lecture.pdf"
Content-Type: application/pdf

< D:/Materials/4t/HCI/Lectures/HCI_Lecture 4.pdf
------WebKitFormBoundary--